server {
  listen 80;
  server_name text-helper;
  server_tokens off;
  root /www;

  location / {
    index index.html index.htm;
    expires 1d;
  }

  location = /service-worker.js {
    expires off;
  }

  location /static {
    expires 7d;
  }

  location ~ \.map$ {
    return 404;
  }

  location = /xivcsv/_search {
    proxy_pass http://172.16.28.10:9200;
  }
}
