server {
  listen 80;
  server_name text-helper;
  server_tokens off;

  location / {
    root /www;
    index index.html index.htm;
    expires 24h;
  }

  location ~ \.map$ {
    return 404;
  }

  location = /xivcsv/_search {
    proxy_pass http://172.16.28.10:9200;
  }
}
